x-shared-env:
  &shared-env
  SICOIN_KEYCLOAK_ISSUER: http://keycloak:8080/realms/sicoin
services:

  sicoin_server:
    profiles:
      - prod
    image: sicoin_server:latest
    container_name: sicoin_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    networks:
      - sicoin-net
    environment:
      <<: *shared-env
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sicoin
      SICOIN_MQTT_HOST: 18.214.23.5:1883
      SICOIN_GOOGLE_MAPS_HOST: https://maps.googleapis.com/maps/api/directions
      SICOIN_GOOGLE_API_KEY: ${SICOIN_GOOGLE_API_KEY}
    depends_on:
      - postgres
  postgres:
    profiles:
      - dev
      - prod
    image: postgres:16
    container_name: postgres-sicoin
    ports:
      - "5432:5432"
    networks:
      - sicoin-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1215141719303060
      POSTGRES_DB: postgres
    volumes:
      - sicoin_postgres_data:/var/lib/postgresql/data

  keycloak:
    profiles:
      - dev
      - prod
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak-sicoin
    ports:
      - "8081:8080"
    networks:
      - sicoin-net
    volumes:
      - sicoin_keycloak_data:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
    command: ["start-dev"]

networks:
  sicoin-net:

volumes:
  sicoin_keycloak_data:
  sicoin_postgres_data:

